name: Form Manager Publish
on:
  push:
    paths:
      - packages/form-manager/**
    tags:
      - '*'
    branches: [main]
jobs:
  publish-form-manager-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build form-manager Docker image
        run: |
              cd packages/form-manager
              docker build . --tag ghcr.io/$OWNER_LC/form-manager:latest
              docker push ghcr.io/$OWNER_LC/form-manager:latest
